version: '3.8'

services:
    database:
        container_name: database
        image: mysql:8.0
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: instagram_like
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        ports:
            - '3306:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - app-network

    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www/app
            - ./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        #            - /var/www/app/vendor/
        #            - /var/www/app/node_modules
        depends_on:
            - database
        networks:
            - app-network

    nginx:
        container_name: nginx
        image: nginx:1.23-alpine
        ports:
            - '80:80'
        volumes:
            - .:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - database
        networks:
            - app-network

networks:
    app-network:
